# -*- coding: utf-8 -*-
"""factorial app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16f1aAsjHt_EWlff2loK9rkYyU6gaZ81W
"""

import streamlit as st
from factorial import fact

def main():
    st.title("Factorial Calculator")

    number = st.number_input(
        "Enter a number:",
        min_value=0,
        max_value=900
    )

    if st.button("Calculate"):
        result = fact(number)
        st.write(f"The factorial of {number} is {result}")
        st.balloons()

if __name__ == "__main__":
    main()

!pip install factorial

!pip install streamlit