# -*- coding: utf-8 -*-
"""factorial.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17thlp-aTLN6TMDCWhShPHQw3t2F44hr6
"""

def fact(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * fact(n - 1)